# Generated by Django 3.0.6 on 2021-10-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20211029_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
